version: '3'
services:
  nginx:
    container_name: sp_nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

  app:
    restart: always
    build: .
    working_dir: .
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    expose:
      - "8087"
    depends_on:
      - nginx
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker
